#!/usr/bin/env python3
"""
Generate the WHO Child Growth Standards LMS reference tables consumed by
packages/shared/src/utils/growth-lms.ts.

Source of truth: the official WHO tables bundled in the `pygrowup2` package
(pip install pygrowup2), which packages the WHO 2006 standards verbatim as
{'male'|'female': {key: {l, m, s}}}. We DO NOT hand-type clinical reference
data — this script transcribes it.

Resolution (chosen to balance fidelity against JS bundle size; the growth-lms
engine linearly interpolates L/M/S between the emitted knots):
  - age-based indicators: monthly (day = round(month * 30.4375)), 0..60 months
    (MUAC/acfa starts at 3 months per WHO)
  - weight-for-length / weight-for-height: every 0.5 cm

Emits:
  packages/shared/src/utils/growth-reference/who-data.ts   (compact data)
  packages/shared/src/utils/growth-reference/who-golden.ts (cross-check fixtures)

Re-run whenever the WHO standards are revised. Requires pygrowup2 installed.
"""
import os
import importlib.util
from decimal import Decimal

TABLES = os.path.expanduser('~/.local/lib/python3.10/site-packages/pygrowup/tables')
OUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'packages', 'shared',
                       'src', 'utils', 'growth-reference')

DAYS_PER_MONTH = 30.4375

# our indicator code  ->  (pygrowup file stem, unitX, sampler)
AGE_INDICATORS = {
    'wfa':   'wfa',   # weight-for-age
    'lhfa':  'lfa',   # length/height-for-age
    'hcfa':  'hcfa',  # head-circumference-for-age
    'bmifa': 'bmifa', # BMI-for-age
    'acfa':  'acfa',  # arm-circumference-for-age (MUAC), starts at 3 months
}
LEN_INDICATORS = {
    'wfl': ('wfl', 45.0, 110.0),  # weight-for-length
    'wfh': ('wfh', 65.0, 120.0),  # weight-for-height
}


def load(stem):
    path = os.path.join(TABLES, 'by_day', stem + '.py')
    spec = importlib.util.spec_from_file_location('m', path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.DATA


def num(d):
    # trim trailing zeros but keep exact WHO precision
    return format(d, 'f').rstrip('0').rstrip('.') if isinstance(d, Decimal) else str(d)


def nearest(table_sex, key):
    """Exact key if present, else the closest available integer day."""
    if key in table_sex:
        return key
    return min(table_sex.keys(), key=lambda k: abs(int(k) - key))


def build_age_rows(stem, start_month):
    data = load(stem)
    out = {'male': [], 'female': []}
    used = {'male': [], 'female': []}
    for sex in ('male', 'female'):
        tbl = data[sex]
        for month in range(start_month, 61):
            day = 0 if month == 0 else round(month * DAYS_PER_MONTH)
            k = nearest(tbl, day)
            r = tbl[k]
            out[sex].append((int(k), r['l'], r['m'], r['s']))
            used[sex].append(int(k))
    return out


def build_len_rows(stem, lo, hi):
    data = load(stem)
    out = {'male': [], 'female': []}
    for sex in ('male', 'female'):
        tbl = data[sex]
        x = lo
        while x <= hi + 1e-9:
            key = Decimal(str(round(x, 1)))
            if key in tbl:
                r = tbl[key]
                out[sex].append((float(key), r['l'], r['m'], r['s']))
            x += 0.5
    return out


def emit_data(all_rows, unit_map):
    lines = [
        '// AUTO-GENERATED by scripts/gen-who-growth-tables.py — DO NOT EDIT BY HAND.',
        '// Source: WHO Child Growth Standards (2006) via the pygrowup2 package.',
        '// Rows are [x, L, M, S]; x is age in DAYS (age indicators) or length/height',
        '// in CM (wfl/wfh). See growth-reference/index.ts for the typed loader.',
        '',
        "import type { GrowthIndicator } from '../growth-lms'",
        "import type { Sex } from '../../types'",
        '',
        'export type RawRow = readonly [number, number, number, number]',
        'export type RawTable = { readonly unitX: \'day\' | \'cm\'; readonly rows: readonly RawRow[] }',
        '',
        'export const WHO_RAW: Record<GrowthIndicator, Record<Sex, RawTable>> = {',
    ]
    for ind, rows in all_rows.items():
        unit = unit_map[ind]
        lines.append(f'  {ind}: {{')
        for sex in ('male', 'female'):
            packed = ', '.join(
                '[%s, %s, %s, %s]' % (num(Decimal(str(x))) if unit == 'cm' else int(x),
                                      num(l), num(m), num(s))
                for (x, l, m, s) in rows[sex]
            )
            lines.append(f"    {sex}: {{ unitX: '{unit}', rows: [{packed}] }},")
        lines.append('  },')
    lines.append('}')
    lines.append('')
    return '\n'.join(lines)


def lms_z(value, l, m, s):
    """WHO-adjusted z, replicated to build golden fixtures (matches growth-lms.ts)."""
    l, m, s = float(l), float(m), float(s)
    z = (pow(value / m, l) - 1) / (l * s) if abs(l) > 1e-7 else (__import__('math').log(value / m) / s)
    if z > 3 or z < -3:
        def sd(zt):
            return m * pow(1 + l * s * zt, 1 / l) if abs(l) > 1e-7 else m * __import__('math').exp(s * zt)
        if z > 3:
            return 3 + (value - sd(3)) / (sd(3) - sd(2))
        return -3 + (value - sd(-3)) / (sd(-2) - sd(-3))
    return z


def emit_golden(all_rows):
    """A handful of (indicator, sex, x, value, expectedZ) fixtures at exact knots."""
    picks = [
        ('wfa', 'male', 5), ('wfa', 'female', 30),
        ('lhfa', 'male', 20), ('hcfa', 'female', 40),
        ('bmifa', 'male', 15), ('acfa', 'female', 25),
    ]
    fixtures = []
    for ind, sex, idx in picks:
        x, l, m, s = all_rows[ind][sex][idx]
        for zt, tag in [(0.0, 'median'), (2.0, 'plus2sd'), (3.5, 'extreme')]:
            # value that should read back as zt (via inverse LMS), then expected z
            l_, m_, s_ = float(l), float(m), float(s)
            if zt <= 3:
                val = (m_ * pow(1 + l_ * s_ * zt, 1 / l_)) if abs(l_) > 1e-7 else m_ * __import__('math').exp(s_ * zt)
            else:
                # extreme: one extra SD-band beyond SD3
                def sd(z):
                    return m_ * pow(1 + l_ * s_ * z, 1 / l_) if abs(l_) > 1e-7 else m_ * __import__('math').exp(s_ * z)
                val = sd(3) + (zt - 3) * (sd(3) - sd(2))
            xv = float(x)
            fixtures.append((ind, sex, xv, round(val, 6), round(lms_z(val, l, m, s), 6)))
    lines = [
        '// AUTO-GENERATED by scripts/gen-who-growth-tables.py — DO NOT EDIT BY HAND.',
        '// Golden cross-check points computed from the WHO source at exact table knots,',
        '// used to prove the TS data + growth-lms engine reproduce WHO z-scores.',
        '',
        "import type { GrowthIndicator } from '../growth-lms'",
        "import type { Sex } from '../../types'",
        '',
        'export type GoldenPoint = {',
        '  indicator: GrowthIndicator; sex: Sex; x: number; value: number; z: number',
        '}',
        '',
        'export const WHO_GOLDEN: GoldenPoint[] = [',
    ]
    for ind, sex, x, val, z in fixtures:
        lines.append(f"  {{ indicator: '{ind}', sex: '{sex}', x: {x}, value: {val}, z: {z} }},")
    lines.append(']')
    lines.append('')
    return '\n'.join(lines)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    all_rows = {}
    unit_map = {}
    for ind, stem in AGE_INDICATORS.items():
        start = 3 if ind == 'acfa' else 0
        all_rows[ind] = build_age_rows(stem, start)
        unit_map[ind] = 'day'
    for ind, (stem, lo, hi) in LEN_INDICATORS.items():
        all_rows[ind] = build_len_rows(stem, lo, hi)
        unit_map[ind] = 'cm'

    with open(os.path.join(OUT_DIR, 'who-data.ts'), 'w') as f:
        f.write(emit_data(all_rows, unit_map))
    with open(os.path.join(OUT_DIR, 'who-golden.ts'), 'w') as f:
        f.write(emit_golden(all_rows))

    counts = {k: len(v['male']) for k, v in all_rows.items()}
    print('Wrote who-data.ts and who-golden.ts. Rows/sex per indicator:', counts)


if __name__ == '__main__':
    main()
