// AUTO-GENERATED by scripts/gen-who-growth-tables.py — DO NOT EDIT BY HAND.
// Golden cross-check points computed from the WHO source at exact table knots,
// used to prove the TS data + growth-lms engine reproduce WHO z-scores.

import type { GrowthIndicator } from '../growth-lms'
import type { Sex } from '../../types'

export type GoldenPoint = {
  indicator: GrowthIndicator; sex: Sex; x: number; value: number; z: number
}

export const WHO_GOLDEN: GoldenPoint[] = [
  { indicator: 'wfa', sex: 'male', x: 152.0, value: 7.5077, z: 0.0 },
  { indicator: 'wfa', sex: 'male', x: 152.0, value: 9.338914, z: 2.0 },
  { indicator: 'wfa', sex: 'male', x: 152.0, value: 10.916048, z: 3.5 },
  { indicator: 'wfa', sex: 'female', x: 913.0, value: 12.7047, z: -0.0 },
  { indicator: 'wfa', sex: 'female', x: 913.0, value: 16.5119, z: 2.0 },
  { indicator: 'wfa', sex: 'female', x: 913.0, value: 20.219685, z: 3.5 },
  { indicator: 'lhfa', sex: 'male', x: 609.0, value: 84.2074, z: 0.0 },
  { indicator: 'lhfa', sex: 'male', x: 609.0, value: 89.835823, z: 2.0 },
  { indicator: 'lhfa', sex: 'male', x: 609.0, value: 94.05714, z: 3.5 },
  { indicator: 'hcfa', sex: 'female', x: 1218.0, value: 48.824, z: 0.0 },
  { indicator: 'hcfa', sex: 'female', x: 1218.0, value: 51.655792, z: 2.0 },
  { indicator: 'hcfa', sex: 'female', x: 1218.0, value: 53.779636, z: 3.5 },
  { indicator: 'bmifa', sex: 'male', x: 457.0, value: 16.4393, z: -0.0 },
  { indicator: 'bmifa', sex: 'male', x: 457.0, value: 19.391157, z: 2.0 },
  { indicator: 'bmifa', sex: 'male', x: 457.0, value: 22.061425, z: 3.5 },
  { indicator: 'acfa', sex: 'female', x: 852.0, value: 15.1811, z: -0.0 },
  { indicator: 'acfa', sex: 'female', x: 852.0, value: 17.921015, z: 2.0 },
  { indicator: 'acfa', sex: 'female', x: 852.0, value: 20.299588, z: 3.5 },
]
